blueprint:
  name: Optimiseur intelligent d'appareil (solaire + heures creuses)
  description: |
    Optimise intelligemment la consommation d’un appareil en priorité solaire.
    Ne consomme en heures creuses que si nécessaire selon l'énergie cible journalière.
  domain: automation

  input:

    appareil_switch:
      name: Interrupteur de l'appareil
      selector:
        entity:
          domain: switch

    appareil_energy:
      name: Capteur Energy total_increasing (kWh)
      selector:
        entity:
          domain: sensor
          device_class: energy

    appareil_power:
      name: Puissance instantanée de l'appareil (W)
      selector:
        entity:
          domain: sensor
          device_class: power

    surplus:
      name: Surplus solaire (W)
      selector:
        entity:
          domain: sensor
          device_class: power

    estimation_jour:
      name: Estimation de production solaire du jour (kWh)
      selector:
        entity:
          domain: sensor
          device_class: energy

    energy_target:
      name: Energie journalière à atteindre (kWh)
      description: Exemple : 3 kWh pour un chauffe-eau 100L
      default: 3
      selector:
        number:
          min: 0.5
          max: 10
          step: 0.1

    heure_debut_hc:
      name: Début des heures creuses
      selector:
        time: {}

    heure_fin_hc:
      name: Fin des heures creuses
      selector:
        time: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: time_pattern
    minutes: "/1"

variables:
  sw: !input appareil_switch
  e_now: "{{ states(!input appareil_energy) | float(0) }}"
  p_now: "{{ states(!input appareil_power) | float(0) }}"
  surplus: "{{ states(!input surplus) | float(0) }}"
  estimation: "{{ states(!input estimation_jour) | float(0) }}"
  target: !input energy_target
  hc_start: !input heure_debut_hc
  hc_end: !input heure_fin_hc

  energy_remaining: "{{ (target - e_now) | max(0) }}"

action:

  - choose:

      # 1) Énergie gratuite : surplus suffisant
      - conditions:
          - condition: template
            value_template: "{{ surplus > p_now }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: "{{ sw }}"

      # 2) Pas assez de soleil → mais en heures creuses
      - conditions:
          - condition: and
            conditions:
              - condition: time
                after: "{{ hc_start }}"
                before: "{{ hc_end }}"
              - condition: template
                value_template: >
                  {{ energy_remaining > estimation }}
                # On chauffe en HC seulement si :
                # énergie restante > production solaire prévue
        sequence:
          - service: switch.turn_on
            target:
              entity_id: "{{ sw }}"

    default:
      - service: switch.turn_off
        target:
          entity_id: "{{ sw }}"
