blueprint:
  name: Optimiseur heures creuses (avec objectif énergie)
  description: >
    Allume un appareil uniquement pendant les heures creuses, 
    avec arrêt automatique lorsque l'énergie quotidienne cible est atteinte.
    Utilise également une estimation de production solaire pour ajuster la décision.
  domain: automation

  input:

    equipment_switch:
      name: Appareil à contrôler
      selector:
        entity:
          domain:
            - switch
            - input_boolean

    energy_sensor:
      name: Capteur d'énergie (PowerCalc)
      description: >
        Capteur cumulatif en kWh généré par PowerCalc (state_class: total_increasing).
      selector:
        entity:
          domain: sensor
          device_class: energy

    production_forecast:
      name: Production solaire prévue (kWh)
      description: >
        Estimation de production solaire journalière (ex : Solcast, SolarForecast).
      selector:
        entity:
          domain: sensor
          device_class: energy

    energy_target:
      name: Energie journalière à atteindre (kWh)
      description: "Exemple : 3 kWh pour un chauffe-eau 100L"
      default: 3
      selector:
        number:
          min: 0.5
          max: 15
          step: 0.1

    hc_start:
      name: Début des heures creuses
      selector:
        time: {}

    hc_end:
      name: Fin des heures creuses
      selector:
        time: {}

mode: restart

# -------------------------------------------------------------------
# TRIGGERS
# -------------------------------------------------------------------

trigger:

  # Début des heures creuses
  - platform: time
    at: !input hc_start

  # Fin des heures creuses
  - platform: time
    at: !input hc_end

  # Mise à jour de l'énergie consommée
  - platform: state
    entity_id: !input energy_sensor

# -------------------------------------------------------------------
# VARIABLES
# -------------------------------------------------------------------

variables:
  energy_sensor: !input energy_sensor
  switch_entity: !input equipment_switch
  forecast: "{{ states( !input production_forecast ) | float(0) }}"
  target: !input energy_target
  current_energy: "{{ states(energy_sensor) | float(0) }}"
  hc_start: !input hc_start
  hc_end: !input hc_end

# -------------------------------------------------------------------
# ACTION
# -------------------------------------------------------------------

action:

  - choose:

      # --------------------------------------------------------------------
      # 1️⃣ Début heures creuses → allumer (si besoin)
      # --------------------------------------------------------------------
      - conditions:
          - condition: time
            at: !input hc_start
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: "{{ switch_entity }}"

      # --------------------------------------------------------------------
      # 2️⃣ Arrêt si énergie cible atteinte (évite surconsommation)
      # --------------------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ current_e
