blueprint:
  name: JustHeuresCreuses – Temps ON garanti
  description: >
    Version A : garantit un temps de fonctionnement minimum sur 24h pendant les heures creuses,
    puis optimise selon les prévisions solaires. Ne dépend pas de l'historique d'énergie.
  domain: automation

  input:
    target_switch:
      name: Équipement à contrôler
      selector:
        entity:
          domain:
            - switch
            - input_boolean

    energy_24h_sensor:
      name: Énergie consommée sur 24h
      description: >
        Capteur représentant l’énergie consommée par l’équipement sur 24h.
        
        👉 Recommandé : créer ce capteur via l’intégration native « Utility Meter »
        directement depuis l’interface Home Assistant.
        
        Étapes :
        - Paramètres > Appareils & services > Assistants > Utility Meter
        - Source : capteur d’énergie cumulatif (kWh)
        - Cycle : Daily
        - Laisser « Delta values » désactivé
        
        Ce capteur correspond à : énergie_actuelle − énergie_au_début_du_jour.
        Il s’agit d’une vue calculée officielle (pas d’une nouvelle mesure),
        nécessaire car les blueprints n’ont pas accès à l’historique (valeur à H-24).
      selector:
        entity:
          domain: sensor

    debug_mode:
      name: Mode debug
      description: Active la journalisation détaillée
      default: false
      selector:
        boolean: {}

trigger:
  - platform: time_pattern
    minutes: "/1"

condition:
  - condition: state
    entity_id: !input heures_creuses_sensor
    state: "on"

variables:
  sw: !input target_switch
  hc: !input heures_creuses_sensor
  counter_minutes: !input minutes_counter
  min_minutes: !input min_minutes
  solar_sensor: !input solar_forecast_sensor
  solar_threshold: !input solar_threshold
  debug: !input debug_mode

  is_on: "{{ is_state(sw, 'on') }}"
  minutes_today: "{{ states(counter_minutes) | int(0) }}"
  solar_forecast: "{{ states(solar_sensor) | float(0) }}"

action:
  # 1. Incrémenter le compteur si l'appareil est ON
  - if:
      - condition: template
        value_template: "{{ is_on }}"
    then:
      - service: counter.increment
        target:
          entity_id: "{{ counter_minutes }}"

  # 2. Décision ON / OFF
  - choose:
      # Priorité : temps minimum non atteint
      - conditions:
          - condition: template
            value_template: "{{ minutes_today < min_minutes }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: "{{ sw }}"

      # Sinon : logique solaire
      - conditions:
          - condition: template
            value_template: "{{ solar_forecast > solar_threshold }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: "{{ sw }}"
    default:
      - service: switch.turn_on
        target:
          entity_id: "{{ sw }}"

  # 3. Debug
  - if:
      - condition: template
        value_template: "{{ debug }}"
    then:
      - service: system_log.write
        data:
          level: info
          message: >
            [JustHeuresCreuses][A][DEBUG]
            HC={{ states(hc) }} | Switch={{ states(sw) }}
            Minutes={{ minutes_today }} / {{ min_minutes }}
            Solar={{ solar_forecast }} kWh (seuil {{ solar_threshold }})
            Decision={{ 'FORCE ON (quota)' if minutes_today < min_minutes else ('OFF (solaire OK)' if solar_forecast > solar_threshold else 'ON') }}

mode: single
