blueprint:
  name: Optimiseur heures creuses (avec objectif énergie + solaire)
  description: >
    Allume un appareil uniquement pendant les heures creuses,
    mais seulement si la production solaire prévue dépasse l'objectif énergie.
    Arrête automatiquement lorsque l'énergie quotidienne cible est atteinte.
  domain: automation

  input:

    equipment_switch:
      name: Appareil à contrôler
      selector:
        entity:
          domain:
            - switch
            - input_boolean

    energy_sensor:
      name: Capteur d'énergie cumulée (kWh)
      description: >
        Capteur cumulatif provenant de PowerCalc (state_class: total_increasing).
      selector:
        entity:
          domain: sensor
          device_class: energy

    production_forecast:
      name: Production solaire prévue (kWh)
      description: >
        Estimation journalière via Solcast / SolarForecast / PVForecast.
      selector:
        entity:
          domain: sensor
          device_class: energy

    energy_target:
      name: Énergie journalière à atteindre (kWh)
      description: "Exemple : 3 kWh pour un chauffe-eau 100L."
      default: 3
      selector:
        number:
          min: 0.5
          max: 15
          step: 0.1

    hc_start:
      name: Début des heures creuses
      selector:
        time: {}

    hc_end:
      name: Fin des heures creuses
      selector:
        time: {}

mode: restart

# -------------------------------------------------------------------
# TRIGGERS
# -------------------------------------------------------------------

trigger:

  - platform: time
    at: !input hc_start

  - platform: time
    at: !input hc_end

  - platform: state
    entity_id: !input energy_sensor

  - platform: state
    entity_id: !input production_forecast

# -------------------------------------------------------------------
# VARIABLES
# -------------------------------------------------------------------

variables:
  # stocker les entités !input dans des variables brutes
  switch_entity: !input equipment_switch
  energy_sensor_entity: !input energy_sensor
  production_forecast_entity: !input production_forecast
  target: !input energy_target
  hc_start: !input hc_start
  hc_end: !input hc_end

  # templates sécurisés utilisant uniquement les variables
  current_energy: "{{ states(energy_sensor_entity) | float(0) }}"
  forecast: "{{ states(production_forecast_entity) | float(0) }}"

# -------------------------------------------------------------------
# ACTIONS
# -------------------------------------------------------------------

action:
  - choose:

      # ------------------------------------------------------------
      # 1️⃣ Début des heures creuses → allumage si :
      #    - production solaire prévue >= cible
      #    - énergie pas encore atteinte
      # ------------------------------------------------------------
      - conditions:
          - condition: time
            at: !input hc_start
          - condition: template
            value_template: "{{ forecast >= target }}"
          - condition: template
            value_template: "{{ current_energy < target }}"
        sequence:
          - service: homeassistant.turn_on
            target:
              entity_id: "{{ switch_entity }}"

      # ------------------------------------------------------------
      # 2️⃣ Arrêt si énergie cible atteinte
      # ------------------------------------------------------------
      - conditions:
          - condition: template
            value_template: "{{ current_energy >= target }}"
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ switch_entity }}"

      # ------------------------------------------------------------
      # 3️⃣ Fin des heures creuses → arrêt systématique
      # ------------------------------------------------------------
      - conditions:
          - condition: time
            at: !input hc_end
        sequence:
          - service: homeassistant.turn_off
            target:
              entity_id: "{{ switch_entity }}"
