blueprint:
  name: JustHeuresCreuses
  description: >
    Décide d'allumer ou d'éteindre un équipement pendant les heures creuses
    selon les prévisions de production solaire et un minimum de fonctionnement journalier.
    Inclut un mode debug avec journalisation détaillée.
  domain: automation

  input:
    target_switch:
      name: Équipement à contrôler
      selector:
        entity:
          domain:
            - switch
            - input_boolean

    energy_sensor:
      name: Capteur d'énergie de l'équipement (kWh cumulatif)
      selector:
        entity:
          domain: sensor

    heures_creuses_sensor:
      name: Capteur Heures Creuses
      description: Doit être ON pendant les heures creuses
      default: binary_sensor.heures_creuses
      selector:
        entity:
          domain: binary_sensor

    solar_forecast_sensor:
      name: Prévision de production solaire sur 24h (kWh)
      default: sensor.energy_production_today_2
      selector:
        entity:
          domain: sensor

    solar_threshold:
      name: Seuil minimum de production solaire (kWh)
      default: 1
      selector:
        number:
          min: 0
          max: 50
          step: 0.1
          unit_of_measurement: kWh

    reference_period:
      name: Période de référence (heures)
      description: Utilisée pour calculer la consommation moyenne
      default: 96
      selector:
        number:
          min: 1
          max: 168
          step: 1
          unit_of_measurement: h

    min_percentage:
      name: Pourcentage minimum de fonctionnement sur 24h
      default: 30
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: "%"

    debug_mode:
      name: Mode debug
      description: Active la journalisation détaillée
      default: false
      selector:
        boolean: {}

trigger:
  - platform: time_pattern
    minutes: "/1"

condition:
  - condition: state
    entity_id: !input heures_creuses_sensor
    state: "on"

variables:
  energy_now: "{{ states(!input energy_sensor) | float(0) }}"
  solar_forecast: "{{ states(!input solar_forecast_sensor) | float(0) }}"
  ref_hours: !input reference_period
  min_pct: !input min_percentage

  # Consommation moyenne journalière estimée
  avg_daily_energy: "{{ (energy_now / ref_hours * 24) if ref_hours > 0 else 0 }}"

  # Energie minimale requise sur 24h
  energy_reference: "{{ avg_daily_energy * (min_pct / 100) }}"

  # Energie sur 24h calculée directement à partir de l'historique
  energy_24h: >-
    {% set history_24h = namespace(val=energy_now) %}
    {% for s in states(!input energy_sensor) | reverse %}
      {% if (as_timestamp(now()) - as_timestamp(s.last_changed)) >= 86400 %}
        {% set history_24h.val = s.state | float(0) %}
        {% break %}
      {% endif %}
    {% endfor %}
    {{ energy_now - history_24h.val }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ solar_forecast > !input solar_threshold or energy_24h >= energy_reference }}
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input target_switch
    default:
      - service: switch.turn_on
        target:
          entity_id: !input target_switch

  - if:
      - condition: state
        entity_id: !input debug_mode
        state: "on"
    then:
      - service: system_log.write
        data:
          level: info
          message: >
            [JustHeuresCreuses][DEBUG]
            Switch={{ states(!input target_switch) }} | HC={{ states(!input heures_creuses_sensor) }}
            SolarForecast={{ solar_forecast }} kWh | SolarThreshold={{ !input solar_threshold }} kWh
            EnergySensor={{ energy_now }} kWh
            Energy24h={{ energy_24h }} kWh | EnergyRef={{ energy_reference }} kWh
            Decision={{ 'OFF' if (solar_forecast > !input solar_threshold or energy_24h >= energy_reference) else 'ON' }}

mode: single
