blueprint:
  name: Gestion intelligente de charge VE + Modes externes
  description: >
    Contrôle la charge d’un véhicule selon plusieurs modes (Auto, Solaire, Heures Creuses,
    Forcé) avec possibilité de changer le mode depuis une entité externe.
  domain: automation

  input:
    mode_selector:
      name: "Sélecteur de mode"
      description: "Input_select permettant de choisir le mode de charge"
      selector:
        entity:
          domain: input_select

    charger_switch:
      name: "Chargeur (switch)"
      selector:
        entity:
          domain: switch

    net_power:
      name: "Puissance nette (W)"
      description: "Production - consommation (valeur positive = surplus)"
      selector:
        entity:
          domain: sensor
          device_class: power

    tesla_soc:
      name: "% de batterie Tesla (%)"
      selector:
        entity:
          domain: sensor
          device_class: battery

    min_soc:
      name: "SOC minimum (%)"
      default: 20
      selector:
        number:
          min: 0
          max: 100
          step: 1

    max_soc:
      name: "SOC maximum (%)"
      default: 80
      selector:
        number:
          min: 0
          max: 100
          step: 1

    surplus_watts:
      name: "Surplus nécessaire pour charger (W)"
      default: 1500
      selector:
        number:
          min: 0
          max: 5000
          step: 100

    off_delay:
      name: "Délai avant arrêt (s)"
      default: 30
      selector:
        number:
          min: 0
          max: 600
          step: 5

mode: restart

trigger:
  - platform: state
    entity_id: !input mode_selector
  - platform: state
    entity_id: !input net_power
  - platform: state
    entity_id: !input tesla_soc

variables:
  mode: "{{ states( input.mode_selector ) }}"
  soc: "{{ states( input.tesla_soc )|float }}"
  net: "{{ states( input.net_power )|float }}"
  min_soc: !input min_soc
  max_soc: !input max_soc
  surplus: !input surplus_watts

condition: []

action:

  - choose:

      ## --- MODE : FORCÉ ---------------------------------------
      - conditions: "{{ mode == 'Force' }}"
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input charger_switch

      ## --- MODE : ARRÊT ---------------------------------------
      - conditions: "{{ mode == 'Off' }}"
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input charger_switch

      ## --- MODE : HEURES CREUSES ------------------------------
      - conditions: "{{ mode == 'Heures Creuses' }}"
        sequence:
          - choose:
              - conditions: "{{ soc < max_soc }}"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input charger_switch
            default:
              - service: switch.turn_off
                target:
                  entity_id: !input charger_switch

      ## --- MODE : SOLAIRE -------------------------------------
      - conditions: "{{ mode == 'Solaire' }}"
        sequence:
          - choose:
              - conditions: >
                  {{ net > surplus and soc < max_soc }}
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input charger_switch

            default:
              - delay: !input off_delay
              - service: switch.turn_off
                target:
                  entity_id: !input charger_switch

      ## --- MODE : AUTO (HC + SOLAIRE + limites SOC) -----------
      - conditions: "{{ mode == 'Auto' }}"
        sequence:
          - choose:
              - conditions: "{{ soc < min_soc }}"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input charger_switch

              - conditions: "{{ net > surplus and soc < max_soc }}"
                sequence:
                  - service: switch.turn_on
                    target:
                      entity_id: !input charger_switch

            default:
              - delay: !input off_delay
              - service: switch.turn_off
                target:
                  entity_id: !input charger_switch
