blueprint:
  name: JustHeuresCreuses v0.5.2
  description: >
    L'objectif est de creer un blueprint qui va prendre la decision d'activer (ou pas) un appareil, en fonction des previsions de la production solaire pendant une periode (heures creuses).
  domain: automation

  input:
    target_switch:
      name: Équipement à contrôler
      description: L'équipement que le blueprint va allumer ou éteindre (switch ou input_boolean).
      selector:
        entity:
          domain:
            - switch
            - input_boolean

    energy_24h_sensor:
      name: Énergie consommée sur 24h
      description: >
          Capteur représentant la consommation réelle de l’équipement sur les dernières 24 heures glissantes.
      
          Pour créer ce capteur (méthode recommandée, fonctionne pour tous les équipements) :
      
          1) Identifier l’entité **index cumulatif** de votre équipement. Ce compteur ne doit jamais se remettre à zéro.
          ex: sensor.equipement_energy qu'il  faudra remplacer a l'etape suivante !
      
          2) Créer un **capteur template** via l’interface Home Assistant ou en YAML.
             rendez-vous dans : Parametres > Appareils et Services > Entrées > Créer une entree
             Choisissez "template" puis "capteur"
             Nom : "Consommation équipement 24h"
             Etat : {% set current = states('sensor.equipement_energy') | float(0) %}
                    {% set history_24h = namespace(val=current) %}
                    {% for s in states.sensor if s.entity_id == 'sensor.equipement_energy' %}
                    {% if s.last_changed and (as_timestamp(now()) - as_timestamp(s.last_changed)) >= 86400 %}
                    {% set history_24h.val = s.state | float(0) %}
                    {% break %}
                    {% endif %}
                    {% endfor %}
                    {{ (current - history_24h.val) | float(0) }}
              Unité:kWh
              Classe d'appareil: Energie
              Classe d'état : Total
              Appareil : votre equipement (si possible)
              
          3) Enregistrer le capteur. selectionne le dans le blueprint.
          ❌ Ne pas utiliser un compteur Utility Meter journalier, qui se remet à zéro à minuit
          et donnera une valeur incorrecte pendant les heures creuses nocturnes.
      selector:
        entity:
          domain: sensor    

    heures_creuses_sensor:
      name: Capteur Heures Creuses
      description: Capteur binaire indiquant la période des heures creuses (ON = heures creuses actives).
      default: binary_sensor.heures_creuses
      selector:
        entity:
          domain: binary_sensor

    min_energy_reference:
      name: Énergie minimale à assurer sur 24h (kWh)
      description: Seuil minimal vital d’énergie que l’équipement doit avoir consommé sur 24h.
      default: 3
      selector:
        number:
          min: 0
          max: 20
          step: 0.1
          unit_of_measurement: kWh
    
    solar_forecast_sensor:
      name: Prévision de production solaire sur 24h (kWh)
      description: Capteur donnant la prévision d’énergie solaire disponible pour la journée.
      default: sensor.energy_production_today
      selector:
        entity:
          domain: sensor

    solar_threshold:
      name: Seuil minimum de production solaire (kWh)
      description: Si la prévision solaire dépasse ce seuil, l’équipement peut être éteint même si le minimum journalier est atteint.
      default: 1
      selector:
        number:
          min: 0
          max: 50
          step: 0.1
          unit_of_measurement: kWh

    debug_mode:
      name: Mode debug
      description: >
        Active la journalisation détaillée du fonctionnement du blueprint. 
        Les logs sont envoyés vers le Journal système de Home Assistant (Paramètres > Système > Journaux) avec le tag [JustHeuresCreuses][DEBUG].
      default: false
      selector:
        boolean: {}

trigger:
  - platform: time_pattern
    minutes: "/1"

condition:
  - condition: state
    entity_id: !input heures_creuses_sensor
    state: "on"

variables:
  sw: !input target_switch
  hc: !input heures_creuses_sensor
  energy_24h: !input energy_24h_sensor
  solar_sensor: !input solar_forecast_sensor
  solar_threshold: !input solar_threshold
  min_energy_ref: !input min_energy_reference
  debug: !input debug_mode

  energy_today: "{{ states(energy_24h) | float(0) }}"
  solar_forecast: "{{ states(solar_sensor) | float(0) }}"
  hc_state: "{{ states(hc) }}"
  sw_state: "{{ states(sw) }}"
  sw_domain: "{{ sw.split('.')[0] }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ energy_today < min_energy_ref }}
        sequence:
          - service: >
              {% if sw_domain == 'switch' %}
              switch.turn_on
              {% elif sw_domain == 'input_boolean' %}
              input_boolean.turn_on
              {% endif %}
            target:
              entity_id: "{{ sw }}"

      - conditions:
          - condition: template
            value_template: >
              {{ solar_forecast > solar_threshold }}
        sequence:
          - service: >
              {% if sw_domain == 'switch' %}
              switch.turn_off
              {% elif sw_domain == 'input_boolean' %}
              input_boolean.turn_off
              {% endif %}
            target:
              entity_id: "{{ sw }}"

    default:
      - service: >
          {% if sw_domain == 'switch' %}
          switch.turn_on
          {% elif sw_domain == 'input_boolean' %}
          input_boolean.turn_on
          {% endif %}
        target:
          entity_id: "{{ sw }}"

  - if:
      - condition: template
        value_template: "{{ debug }}"
    then:
      - service: system_log.write
        data:
          level: warning
          message: >
            [JustHeuresCreuses][DEBUG] HC={{ hc_state }} | Switch={{ sw_state }} | Energy24h={{ energy_today }} kWh (min {{ min_energy_ref }}) | Solar={{ solar_forecast }} kWh (seuil {{ solar_threshold }}) | Decision={{ 'ON (needs energy)' if energy_today < min_energy_ref else ('OFF (solar ok)' if solar_forecast > solar_threshold else 'ON (no solar)') }}

mode: single
