blueprint:
  name: JustHeuresCreuses
  description: >
    L'objectif est de creer un blueprint qui va prendre la decision d'activer (ou pas) un appareil, en fonction des previsions de la production solaire pendant une periode (heures creuses).
  domain: automation

  input:
    target_switch:
      name: Équipement à contrôler
      description: L'équipement que le blueprint va allumer ou éteindre (switch ou input_boolean).
      selector:
        entity:
          domain:
            - switch
            - input_boolean

    heures_creuses_sensor:
      name: Capteur Heures Creuses
      description: Capteur binaire indiquant quand c'est la période des heures creuses (ON = heures creuses actives).
      default: binary_sensor.heures_creuses
      selector:
        entity:
          domain: binary_sensor

    energy_24h_sensor:
      name: Énergie consommée sur 24h
      description: >
        Capteur représentant l’énergie consommée par l’équipement sur 24h.
        Recommandé : créer via l’intégration « Utility Meter » depuis l’interface Home Assistant.
      selector:
        entity:
          domain: sensor

    solar_forecast_sensor:
      name: Prévision de production solaire sur 24h (kWh)
      description: Capteur donnant la prévision d’énergie solaire disponible pour la journée.
      default: sensor.energy_production_today_2
      selector:
        entity:
          domain: sensor

    solar_threshold:
      name: Seuil minimum de production solaire (kWh)
      description: Si la prévision solaire dépasse ce seuil, l’équipement peut être éteint même si le minimum journalier n’est pas atteint.
      default: 1
      selector:
        number:
          min: 0
          max: 50
          step: 0.1
          unit_of_measurement: kWh

    min_energy_reference:
      name: Énergie minimale à assurer sur 24h (kWh)
      description: Seuil minimal de consommation sur 24h que l’équipement doit atteindre.
      default: 3
      selector:
        number:
          min: 0
          max: 20
          step: 0.1
          unit_of_measurement: kWh

    debug_mode:
      name: Mode debug
      description: Active la journalisation détaillée pour suivre toutes les variables et décisions du blueprint.
      default: false
      selector:
        boolean: {}

trigger:
  - platform: time_pattern
    minutes: "/1"

condition:
  - condition: state
    entity_id: !input heures_creuses_sensor
    state: "on"

variables:
  sw: !input target_switch
  hc: !input heures_creuses_sensor
  energy_24h: !input energy_24h_sensor
  solar_sensor: !input solar_forecast_sensor
  solar_threshold: !input solar_threshold
  min_energy_ref: !input min_energy_reference
  debug: !input debug_mode

  energy_today: "{{ states(energy_24h) | float(0) }}"
  solar_forecast: "{{ states(solar_sensor) | float(0) }}"
  hc_state: "{{ states(hc) }}"
  sw_state: "{{ states(sw) }}"
  sw_domain: "{{ sw.split('.')[0] }}"

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ solar_forecast > solar_threshold or energy_today >= min_energy_ref }}
        sequence:
          - service: >
              {% if sw_domain == 'switch' %}
              switch.turn_off
              {% elif sw_domain == 'input_boolean' %}
              input_boolean.turn_off
              {% endif %}
            target:
              entity_id: "{{ sw }}"
    default:
      - service: >
          {% if sw_domain == 'switch' %}
          switch.turn_on
          {% elif sw_domain == 'input_boolean' %}
          input_boolean.turn_on
          {% endif %}
        target:
          entity_id: "{{ sw }}"

  - if:
      - condition: template
        value_template: "{{ debug }}"
    then:
      - service: system_log.write
        data:
          level: info
          message: >
            [JustHeuresCreuses][DEBUG]
            HC={{ hc_state }}
            | Switch={{ sw_state }}
            Energy24h={{ energy_today }} kWh (min {{ min_energy_ref }})
            | Solar={{ solar_forecast }} kWh (seuil {{ solar_threshold }})
            | Decision={{ 'OFF' if (solar_forecast > solar_threshold or energy_today >= min_energy_ref) else 'ON' }}

mode: single
